### ISSUE TITLE
error in localhost

### ISSUE THREAD

**Issue by Harshavardhan20201** [rabindralamsal/Complete-Web-Based-Inventory-System#2]
Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\inventory\php_action\db_connect.php on line 8
Connection Failed : Access denied for user 'root'@'localhost' (using password: YES
PLEASE HELP ME CZ I HAVE A PROJECT IN 1 DAY

**Comment by KareemEhab17** [comment]
Change the database connection in php_action\db_connect.php password to '' remove the 'root' and make it '' if you are using localhost but leave the username 'root'
